version: 1

formatters:
  standard:
    format: '%(message)s'
    style: '%'

  base:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    style: '%'


handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO

  gameplay_config:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logger/logs/gameplay.log
    mode: 'a'

  websockket_config:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logger/logs/websocket.log
    mode: 'a'

  valuenetwork_config:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logger/logs/valuenetwork.log
    mode: 'a'

  moveanalysis_config:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logger/logs/moveanalysis.log
    mode: 'a'

  gamehandler_config:
    class: logging.FileHandler
    formatter: standard
    level: INFO
    filename: logger/logs/gamehandler.log
    mode: 'a'

root:
  level: INFO
  handlers: [console]

loggers:
  gameplay: 
    level: INFO
    handlers: [gameplay_config, console]
    propagate: no

  websocket:
    level: INFO
    handlers: [websockket_config, console]
    propagate: no

  valuenetwork:
    level: INFO
    handlers: [valuenetwork_config]
    propagate: no

  moveAnalysis:
    level: INFO
    handlers: [moveanalysis_config]
    propagate: no

  GameHandler:
    level: INFO
    handlers: [gamehandler_config]
    propagate: no
